name: Verify Issue Workflow

on:
  issues:
    types: [opened, closed]

jobs:
  verify_opened_issue:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Get Opened Issue Informations
        run: echo "Github Env ${{ toJSON(github.event) }}"
  verify_closed_issue:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Get Closed Issue Informations
        run: echo "GitHub Env ${{toJSON(github.event)}}"